### ISSUE TITLE
Twilio API not included in Repository

### ISSUE THREAD

**Issue by organicmediumroast** [446f6e616c64/Irohs_Messenger#9]
Twilio API not included in repository.

When trying to test out the feature, it comes up with this message:
"
Traceback (most recent call last):
  File "./main.py", line 12, in <module>
    from twilio.rest import Client
ModuleNotFoundError: No module named 'twilio'
"

**Comment by 446f6e616c64** [comment]
This will get into the documentation. For now perform the following actions
sudo apt-get install python3-pip
sudo pip install twilio

**Comment by 446f6e616c64** [comment]
Documentation has been updated with instructions on how to install twilio python module.
